name: Build and Deploy Hakyll Site

on:
  push:
    branches: [main]
    paths:
      - 'site/**'
      - '.github/workflows/deploy-site.yml'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull Docker image
        run: docker pull ghcr.io/${{ github.repository }}:latest

      - name: Build site with Docker
        run: |
          docker run --rm -v "${{ github.workspace }}/site:/site" ghcr.io/${{ github.repository }}:latest

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site/_site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

